export { AgentLoop, LOOP_HARD_PAUSE_AT, MAX_CONSECUTIVE_TIMEOUTS, QUESTION_GATE_DIRECTIVE, STALL_ESCALATE_AT, STALL_LIMIT, commandLineForCall, parseAction, thoughtFromMessage, type AgentLoopOptions } from './agent-loop.ts';
export { schemaSummary, toolCallParseErrorOutput, validateToolCallArguments, type ToolCallValidation } from './tool-call-validation.ts';
export { interpretTask } from './interpreter.ts';
export {
  BOOTSTRAP_PROBE_TOOLS,
  DEFAULT_SCAFFOLD_HOST,
  MISE_PACKAGE_BY_TOOL,
  SCAFFOLD_RECIPES,
  UNSUPPORTED_FRAMEWORK_MENTIONS,
  commandLineTokens,
  creationCompletionRefusal,
  creationSpecificity,
  deriveTaskTargetDir,
  detectCreationGoal,
  detectScaffoldRequest,
  detectUnsupportedFramework,
  djangoProjectName,
  explicitTargetFolder,
  extractTargetDir,
  recordedTargetDir,
  sessionAnchorDirective,
  flutterProjectName,
  formatToolchainSummary,
  missingToolchains,
  pathInsideTarget,
  planDocumentFolder,
  probeToolchains,
  questionGateAppliesToGoal,
  renderDatabasePlaybook,
  renderDockerGeneratorLine,
  renderScaffoldPlaybook,
  renderToolchainAcquisition,
  renderUnsupportedPlaybook,
  scaffoldApprovalChain,
  scaffoldChainStepFor,
  scaffoldMarkerPresent,
  summarizeCommandFailure,
  workspaceRelativePath,
  type CreationCompletionEvidence,
  type CreationGoal,
  type CreationRefusal,
  type CreationSpecificity,
  type ScaffoldChainStep,
  type ScaffoldHostInfo,
  type ScaffoldMatch,
  type ScaffoldRecipe,
  type ScaffoldRecipeCategory,
  type ScaffoldRecipeId,
  type TaskTargetInput,
  type ToolchainProbe,
  type ToolchainProbeFn,
} from './scaffold.ts';
export { DEFAULT_PLAN_STEPS, createPlan, isDefaultPipeline, replan, scaffoldPlanSteps } from './planner.ts';
export {
  DefaultContextManager,
  CONDENSED_TOOL_OUTPUT,

  type SlideTaskParams,
  MAX_PINNED_FILES_IN_PROMPT,
  MAX_PINNED_LINES_PER_FILE,
  MAX_PINNED_TOTAL_CHARS,
  MAX_SKILL_DESCRIPTION_CHARS,
  MAX_SKILL_INDEX_CHARS,
  condenseToolOutputs,
  contextMeter,
  estimateMessageTokens,
  truncate,
  type ContextManagerOptions,
} from './context.ts';
export {
  MAX_MENTION_DIR_ENTRIES,
  MAX_MENTION_FILE_CHARS,
  MAX_MENTION_PATHS,
  MAX_MENTION_TOTAL_CHARS,
  extractMentionPaths,
  resolveMentionSection,
} from './mentions.ts';
export {
  LoopGuard,
  LOOP_WINDOW_SIZE,
  REPEAT_SUPPRESSED_OUTPUT,
  explorationKey,
  explorationSuppressedNote,
  loopGuidanceNote,
  normalizeExplorationPath,
  skillAlreadyLoadedNote,
  stableSerialize,
  toolCallSignature,
  type LoopGuardDecision,
  type LoopGuardObservation,
  type LoopRepeatKind,
} from './loop-guard.ts';
export { GLOBAL_RULES_LABEL, loadProjectRules, MAX_RULES_CHARS, PROJECT_RULES_FILES, type ProjectRules, type ProjectRulesOptions } from './rules.ts';
export {
  HOOKS_CONFIG_RELATIVE_PATH,
  hookMatches,
  hookNoteLine,
  loadHooksConfig,
  runPostToolHooks,
  runPreToolHooks,
  type HookExecution,
  type HookPhase,
  type HookRule,
  type HooksConfig,
  type LoadHooksResult,
  type PostToolHookOutcome,
  type PreToolHookOutcome,
} from './hooks.ts';
export {
  MAX_REVIEW_DIFF_CHARS,
  REVIEW_READ_ONLY_TOOLS,
  buildReviewMessages,
  parseReviewFindings,
  reviewDiff,
  unstagedDiff,
  type ReviewFinding,
  type ReviewResult,
} from './review.ts';
export {
  CONVERSATIONAL_SYSTEM_PROMPT,
  QUESTION_SYSTEM_PROMPT,
  answerConversational,
  answerQuestion,
  classifyChatIntent,
  conversationalFallbackReply,
  gatherWorkspaceContext,
  questionFallbackReply,
  type AnswerQuestionOptions,
  type ChatIntent,
} from './conversation.ts';
export { handleObservation } from './observation.ts';
export {
  DEFAULT_TOOL_OUTPUT_LIMITS,
  TOOL_OUTPUT_HEAD_RATIO,
  TOOL_OUTPUT_MAX_CHARS,
  TOOL_OUTPUT_MAX_LINES,
  resolveToolOutputLimits,
  shapeToolOutput,
  truncateHeadTail,
  writeSpillFile,
  type ShapeToolOutputOptions,
  type ShapedToolOutput,
  type ToolOutputLimits,
} from './tool-output.ts';
export {
  OUTPUT_COMPRESSION_MIN_CHARS,
  OUTPUT_COMPRESSION_MIN_LINES,
  compressCommandOutput,
  detectCommandOutputFamily,
  type CommandOutputCompression,
  type CommandOutputCompressionInput,
  type CommandOutputFamily,
} from './output-compression.ts';
export { evaluateStopConditions, noProgressCondition } from './stop.ts';
export {
  PROMPT_FAMILIES,
  detectPromptFamily,
  normalizePromptFamilySetting,
  parsePromptFamilySetting,
  promptFamilyFragment,
  resolvePromptFamily,
} from './prompt-dialects.ts';
export type {
  Action,
  CompleteAction,
  ContextManager,
  Observation,
  ObservationHandler,
  Planner,
  ReplanAction,
  StopAction,
  StopCondition,
  StopPolicy,
  StopReason,
  TaskInterpreter,
  ToolAction,
  ToolExecutor,
} from './types.ts';
