"""add async task payload and unified api keys

Revision ID: 026c0ba8b35c
Revises: e4c7a9b2d6f1
Create Date: 2026-09-02 17:04:48.835744

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "026c0ba8b35c"
down_revision: str | None = "e4c7a9b2d6f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column(
            "id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("secret_hash", sa.String(length=512), nullable=False),
        sa.Column("token_encrypted", sa.String(length=1024), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_created_by_id"),
        "api_keys",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_keys_expires_at"),
        "api_keys",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_keys_revoked_at"),
        "api_keys",
        ["revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False
    )
    tables = set(sa.inspect(op.get_bind()).get_table_names())
    if "access_tokens" in tables:
        op.drop_table("access_tokens")
    if "async_tasks" in tables:
        async_task_columns = {
            column["name"]
            for column in sa.inspect(op.get_bind()).get_columns("async_tasks")
        }
        if "payload" not in async_task_columns:
            op.add_column(
                "async_tasks", sa.Column("payload", sa.JSON(), nullable=True)
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("async_tasks", "payload")
    op.create_table(
        "access_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_access_tokens_user_id"),
        "access_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_tokens_token"),
        "access_tokens",
        ["token"],
        unique=False,
    )
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_revoked_at"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_expires_at"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_created_by_id"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
