/**
 * Daedalus Core — public API.
 *
 * Phase 1 exposes foundation primitives only: shared contracts, the in-process
 * event bus, structured logging, typed settings, and per-task persistence.
 * Agent/tool/LLM logic is intentionally absent (PLAN.md Phase 1 scope).
 *
 * Contracts:  TaskSpec, Plan, PlanStep, ToolCall, ToolResult, Event,
 *             ValidationResult, RecoveryAction, FinalReport, EVENT_TYPES
 * Runtime:    EventBus, TaskStore, createLogger, loadSettings, redactSettings
 */
export {
  AGENT_MODES,
  EVENT_TYPES,
  type AgentMode,
  type Attachment,
  type AttachmentKind,
  type ChildTask,
  type ChildTaskBudget,
  type EditFormat,
  type Event,
  type EventType,
  type FinalReport,
  type ModelStrategy,
  type ModelTier,
  type Plan,
  type PlanStep,
  type PlanStepStatus,
  type PromptFamily,
  type PromptFamilySetting,
  type ProviderConfig,
  type ProviderConfigPublic,
  type RecoveryAction,
  type ReviewGateReport,
  type SlashCommand,
  type TaskSpec,
  type TaskState,
  type ToolCall,
  type ToolModePolicy,
  type ToolProtocol,
  type ToolResult,
  type ToolResultStatus,
  type ToolVisibility,
  type ValidationCheck,
  type ValidationResult,
  type WorktreeReport,
} from "./contracts.ts";

export { EventBus, emitEvent, type EventHandler, type EventTarget } from "./events.ts";

export {
  createLogger,
  type LogLevel,
  type Logger,
} from "./logger.ts";

export {
  loadSettings,
  normalizeEditFormat,
  parseEditFormat,
  redactSettings,
  resolveDaedalusHome,
  type Env,
  type Settings,
} from "./settings.ts";

export { TaskStore } from "./persistence.ts";

export {
  MAX_PINS,
  PINS_FILE_NAME,
  loadPins,
  pinsFilePath,
  sanitizePins,
  savePins,
} from "./pins.ts";

export {
  ansiPalette,
  bold,
  dim,
  fg,
  getPalette,
  modeAccent,
  palette,
  paletteLight,
  rgb,
  supportsColor,
  type ModeAccentKey,
  type PaletteName,
} from "./theme.ts";

export {
  EXIT_CODES,
  TaskRunner,
  exitCodeFor,
  planDocumentsFromEvents,
  type ExtensionStatus,
  type RunOptions,
  type RunOutcome,
  type RunResult,
  type TaskRunnerOptions,
} from "./runtime.ts";

export {
  McpClient,
  McpManager,
  loadMcpConfig,
  MCP_CONFIG_RELATIVE_PATH,
  type McpCallResult,
  type McpRemoteTool,
  type McpServerConfig,
  type McpServerStatus,
} from "./mcp/index.ts";

export {
  LspClient,
  LspManager,
  formatDiagnostic,
  loadLspConfig,
  LSP_CONFIG_RELATIVE_PATH,
  type LspDiagnostic,
  type LspServerConfig,
  type LspServerStatus,
} from "./lsp/index.ts";

export {
  MAX_SKILLS_IN_PROMPT,
  SkillRegistry,
  createReadSkillTool,
  daedalusGlobalSkillsDir,
  dedupeSkillsByName,
  formatSkillOrigin,
  globalSkillSearchDirs,
  loadSkills,
  parseSkillMarkdown,
  resolveSkillSearchDirs,
  workspaceSkillsDir,
  WORKSPACE_SKILLS_RELATIVE_PATH,
  type Skill,
  type SkillDirOptions,
  type SkillInfo,
  type SkillOrigin,
  type SkillSearchDir,
} from "./skills/index.ts";

export {
  CommandValidator,
  VALIDATION_PROFILE_RELATIVE_PATH,
  aggregateValidation,
  completionGate,
  decideRecovery,
  discoverChecks,
  discoverScopedChecks,
  loadValidationProfile,
  normalizeError,
  profileCommands,
  splitCommandLine,
  type NormalizedError,
  type RecoveryContext,
  type RecoveryPolicy,
  type ScopedCheckDiscovery,
  type ValidationCommand,
  type ValidationProfile,
  type ValidationProfileCheck,
  type Validator,
  type ValidatorOptions,
  validationFailed,
  validationFailureSignature,
  validationPassed,
  validationSatisfied,
} from "./validation/index.ts";

export {
  ApprovalBroker,
  ExecutionHarness,
  DEFAULT_APPROVAL_TIMEOUT_MS,
  DEFAULT_HARNESS_CONFIG,
  approvalPatternKey,
  buildApprovalPreview,
  commandLineOf,
  rememberPatternFor,
  resolveApprovalTimeoutMs,
  type ApprovalCallback,
  type ApprovalDecision,
  type ApprovalDecisionInput,
  type ApprovalPolicy,
  type ApprovalPreview,
  type ApprovalRememberPattern,
  type ApprovalRequestInfo,
  type ApprovalResult,
  type HarnessConfig,
  type HarnessContext,
  type HarnessEvent,
  type PermissionKey,
  type ResourceUsage,
} from "./execution/index.ts";

export {
  DEFAULT_TOOLS,
  IGNORED_DIRECTORY_NAMES,
  MAX_LIST_ENTRIES,
  ToolRegistry,
  applySearchReplace,
  createDefaultRegistry,
  createDirTool,
  changedLineCounts,
  diffLines,
  editFileTool,
  editSearchReplaceTool,
  globTool,
  grepTool,
  listDirTool,
  parseSearchReplaceBlocks,
  pathInWorkspace,
  readFileTool,
  renderPatch,
  runCommandTool,
  walkTreeLines,
  writeFileTool,
  type AppliedSearchReplace,
  type DiffLine,
  type ModelToolSchema,
  type ParsedSearchReplace,
  type SearchReplaceBlock,
  type ToolDefinition,
  type ToolExecutionContext,
} from "./tools/index.ts";

export {
  AGENT_MODE_ORDER,
  ASK_USER_TOOL_NAME,
  DEFAULT_QUESTION_TIMEOUT_MS,
  MODE_DESCRIPTIONS,
  ModeController,
  OrchestratorRunner,
  PLAN_DOCUMENTS_ROOT,
  PLAN_DOCUMENT_TEMPLATE,
  PROVIDER_PRESETS,
  ProviderRegistry,
  ProviderRegistryStore,
  QuestionBroker,
  SLASH_COMMANDS,
  SlashCommandRegistry,
  childTaskFromInput,
  MODE_PERMISSION_MATRIX,
  classifyToolName,
  createAskUserTool,
  cycleAgentMode,
  decomposeTask,
  isPlanDocumentPath,
  isReadOnlyMode,
  isToolCallDenied,
  isToolVisible,
  maskApiKey,
  modeDenialMessage,
  modeIntent,
  modePromptContract,
  nextAgentMode,
  normalizeQuestionOptions,
  parseSlashCommand,
  questionResultOutput,
  restrictMode,
  resolveQuestionTimeoutMs,
  sanitizeProviderInput,
  seedProviderFromSettings,
  slashCommandSuggestions,
  toPublicProvider,
  toolCallPolicy,
  toolModePolicy,
  type AskUserToolDeps,
  type ChildTaskExecution,
  type ChildTaskExecutor,
  type ChildTaskInput,
  type ModeChange,
  type OrchestratorResult,
  type ParsedSlashCommand,
  type ProviderPreset,
  type SlashCommandContext,
  type SlashCommandResult,
  type UserQuestionInfo,
  type UserQuestionOption,
  type UserQuestionOutcome,
  type UserQuestionResult,
} from "./interaction/index.ts";

export {
  AgentLoop,
  CONDENSED_TOOL_OUTPUT,
  CONVERSATIONAL_SYSTEM_PROMPT,
  MAX_MENTION_DIR_ENTRIES,
  MAX_MENTION_FILE_CHARS,
  MAX_MENTION_PATHS,
  MAX_MENTION_TOTAL_CHARS,
  MAX_PINNED_FILES_IN_PROMPT,
  MAX_PINNED_LINES_PER_FILE,
  MAX_PINNED_TOTAL_CHARS,
  PROMPT_FAMILIES,
  QUESTION_SYSTEM_PROMPT,
  DefaultContextManager,
  GLOBAL_RULES_LABEL,
  HOOKS_CONFIG_RELATIVE_PATH,
  LOOP_WINDOW_SIZE,
  LoopGuard,
  MAX_REVIEW_DIFF_CHARS,
  MAX_RULES_CHARS,
  PROJECT_RULES_FILES,
  REPEAT_SUPPRESSED_OUTPUT,
  REVIEW_READ_ONLY_TOOLS,
  type ContextManagerOptions,
  type HookExecution,
  type HookPhase,
  type HookRule,
  type HooksConfig,
  type LoadHooksResult,
  type LoopGuardDecision,
  type LoopGuardObservation,
  type LoopRepeatKind,
  type PostToolHookOutcome,
  type PreToolHookOutcome,
  type ProjectRules,
  type ProjectRulesOptions,
  type ReviewFinding,
  type ReviewResult,
  buildReviewMessages,
  answerConversational,
  answerQuestion,
  classifyChatIntent,
  condenseToolOutputs,
  conversationalFallbackReply,
  detectPromptFamily,
  extractMentionPaths,
  gatherWorkspaceContext,
  normalizePromptFamilySetting,
  parsePromptFamilySetting,
  promptFamilyFragment,
  questionFallbackReply,
  resolveMentionSection,
  resolvePromptFamily,
  contextMeter,
  createPlan,
  estimateMessageTokens,
  evaluateStopConditions,
  handleObservation,
  hookMatches,
  hookNoteLine,
  interpretTask,
  loadHooksConfig,
  loadProjectRules,
  loopGuidanceNote,
  noProgressCondition,
  parseAction,
  parseReviewFindings,
  replan,
  resolveToolOutputLimits,
  reviewDiff,
  runPostToolHooks,
  runPreToolHooks,
  shapeToolOutput,
  stableSerialize,
  thoughtFromMessage,
  toolCallSignature,
  truncate,
  truncateHeadTail,
  unstagedDiff,
  DEFAULT_TOOL_OUTPUT_LIMITS,
  TOOL_OUTPUT_HEAD_RATIO,
  TOOL_OUTPUT_MAX_CHARS,
  TOOL_OUTPUT_MAX_LINES,
  type Action,
  type AgentLoopOptions,
  type AnswerQuestionOptions,
  type ChatIntent,
  type CompleteAction,
  type ContextManager,
  type Observation,
  type ObservationHandler,
  type Planner,
  type ReplanAction,
  type ShapeToolOutputOptions,
  type ShapedToolOutput,
  type StopAction,
  type StopCondition,
  type StopPolicy,
  type StopReason,
  type TaskInterpreter,
  type ToolAction,
  type ToolExecutor,
  type ToolOutputLimits,
} from "./agent/index.ts";

export {
  guardEditedFile,
  type EditGuardLsp,
  type EditGuardOptions,
  type EditGuardOutcome,
} from "./agent/edit-guard.ts";

export {
  DEFAULT_LLM_TIMEOUT_MS,
  DEFAULT_MODEL_COOLDOWN_MS,
  DEFAULT_RETRY_POLICY,
  LLMAuthError,
  LLMContentPolicyError,
  LLMError,
  LLMFormatError,
  LLMRateLimitError,
  LLMTimeoutError,
  ModelPoolProvider,
  OpenAICompatProvider,
  TextProtocolProvider,
  asModelController,
  buildPrompt,
  classifyLLMError,
  classifyProviderError,
  clearProviders,
  createProviderForConfig,
  createProviderFromSettings,
  defaultTemplate,
  estimateTokens,
  getProvider,
  hasUpstreamFailureMarker,
  instrumentProvider,
  isFatalLLMError,
  isModelPoolRetryableError,
  isRetryable,
  isTransientLLMError,
  modelPoolFailureReason,
  normalizeModelList,
  normalizeModelTiers,
  normalizeToolProtocol,
  parseModelStrategy,
  parseModelTiers,
  parseTextToolCalls,
  parseToolProtocol,
  protocolBlock,
  registerProvider,
  strongestModelFor,
  systemMessage,
  tierRankForPhase,
  toTextMessages,
  userMessage,
  withRetry,
  type ChatOptions,
  type ChatResponse,
  type ContentBlock,
  type ImageContent,
  type LLMProvider,
  type LLMErrorKind,
  type Message,
  type ModelController,
  type ModelPhase,
  type ModelPoolOptions,
  type ModelPoolSwitch,
  type OpenAICompatOptions,
  type PromptSection,
  type PromptTemplate,
  type ProtocolSwitchInfo,
  type RetryPolicy,
  type Role,
  type StreamChunk,
  type TextContent,
  type TextParseResult,
  type TextProtocolOptions,
  type ToolDefinition as LLMToolDefinition,
} from "./providers/index.ts";

export {
  AgentRegistry,
  WORKSPACE_AGENTS_RELATIVE_PATH,
  agentNameFromPath,
  loadAgents,
  parseAgentMarkdown,
  workspaceAgentsDir,
  type AgentDefinition,
} from "./agents/index.ts";

export {
  applyTaskWorktree,
  createTaskWorktree,
  isGitWorkTree,
  removeTaskWorktree,
  taskBranchName,
  worktreeChangedFiles,
  worktreePatch,
  worktreePathFor,
  type WorktreeRecord,
} from "./worktree.ts";

export { VERSION } from "./version.ts";
