/**
 * Daedalus Core — public API.
 *
 * Phase 1 exposes foundation primitives only: shared contracts, the in-process
 * event bus, structured logging, typed settings, and per-task persistence.
 * Agent/tool/LLM logic is intentionally absent (PLAN.md Phase 1 scope).
 *
 * Contracts:  TaskSpec, Plan, PlanStep, ToolCall, ToolResult, Event,
 *             ValidationResult, RecoveryAction, FinalReport, EVENT_TYPES
 * Runtime:    EventBus, TaskStore, createLogger, loadSettings, redactSettings
 */
export {
  AGENT_MODES,
  EVENT_TYPES,
  type AgentMode,
  type Attachment,
  type AttachmentKind,
  type ChildTask,
  type ChildTaskBudget,
  type EditFormat,
  type Event,
  type EventType,
  type FinalReport,
  type ModelStrategy,
  type ModelTier,
  type Plan,
  type PlanStep,
  type PlanStepStatus,
  type PromptFamily,
  type TailorEscalatedPayload,
  type PromptFamilySetting,
  type ProviderConfig,
  type ProviderConfigPublic,
  type RecoveryAction,
  type ReviewGateReport,
  type SlashCommand,
  type TaskDomain,
  type TaskSpec,
  type TaskState,
  type ToolCall,
  type ToolModePolicy,
  type ToolProtocol,
  type ToolResult,
  type ToolResultStatus,
  type ToolVisibility,
  type ValidationCheck,
  type ValidationResult,
  type WorktreeReport,
} from "./contracts.ts";

export { EventBus, emitEvent, type EventHandler, type EventTarget } from "./events.ts";

export {
  createLogger,
  type LogLevel,
  type Logger,
} from "./logger.ts";

export {
  loadSettings,
  normalizeEditFormat,
  parseEditFormat,
  redactSettings,
  resolveDaedalusHome,
  type Env,
  type Settings,
} from "./settings.ts";

export { TaskStore } from "./persistence.ts";

export {
  MAX_PINS,
  PINS_FILE_NAME,
  loadPins,
  pinsFilePath,
  sanitizePins,
  savePins,
} from "./pins.ts";

export {
  ansiPalette,
  bold,
  dim,
  fg,
  getPalette,
  modeAccent,
  palette,
  paletteLight,
  rgb,
  supportsColor,
  type ModeAccentKey,
  type PaletteName,
} from "./theme.ts";

export {
  EXIT_CODES,
  TaskRunner,
  exitCodeFor,
  planDocumentsFromEvents,
  type ExtensionStatus,
  type RunOptions,
  type RunOutcome,
  type RunResult,
  type TaskRunnerOptions,
} from "./runtime.ts";

export {
  McpClient,
  McpManager,
  loadMcpConfig,
  MCP_CONFIG_RELATIVE_PATH,
  type McpCallResult,
  type McpRemoteTool,
  type McpServerConfig,
  type McpServerStatus,
} from "./mcp/index.ts";

export {
  LspClient,
  LspManager,
  formatDiagnostic,
  loadLspConfig,
  withDefaultLspServers,
  defaultTypescriptServer,
  isTypescriptWorkspace,
  TYPESCRIPT_LSP_EXTENSIONS,
  LSP_CONFIG_RELATIVE_PATH,
  type LspDiagnostic,
  type LspServerConfig,
  type LspServerStatus,
} from "./lsp/index.ts";

export {
  MAX_SKILLS_IN_PROMPT,
  SKILLS_CONFIG_RELATIVE_PATH,
  SkillRegistry,
  createReadSkillTool,
  daedalusGlobalSkillsDir,
  dedupeSkillsByName,
  formatSkillOrigin,
  globalSkillSearchDirs,
  isPresentationSkill,
  loadSkillConfig,
  loadSkillInventory,
  loadSkills,
  parseSkillConfig,
  parseSkillMarkdown,
  renderSkillBody,
  resolveSkillSearchDirs,
  setSkillDisabled,
  skillsConfigPath,
  workspaceSkillsDir,
  writeSkillConfig,
  WORKSPACE_SKILLS_RELATIVE_PATH,
  type Skill,
  type SkillConfig,
  type SkillDirOptions,
  type SkillInfo,
  type SkillInventoryEntry,
  type SkillLoadedPayload,
  type SkillOrigin,
  type SkillSearchDir,
} from "./skills/index.ts";

export {
  CommandValidator,
  VALIDATION_PROFILE_RELATIVE_PATH,
  aggregateValidation,
  completionGate,
  decideRecovery,
  discoverChecks,
  discoverScopedChecks,
  discoverTargetChecks,
  loadValidationProfile,
  normalizeError,
  profileCommands,
  splitCommandLine,
  type NormalizedError,
  type RecoveryContext,
  type RecoveryPolicy,
  type ScopedCheckDiscovery,
  type TargetCheckDiscovery,
  type ValidationCommand,
  type ValidationProfile,
  type ValidationProfileCheck,
  type Validator,
  type ValidatorOptions,
  validationFailed,
  validationFailureSignature,
  validationPassed,
  validationSatisfied,
} from "./validation/index.ts";

export {
  ApprovalBroker,
  ExecutionHarness,
  DEFAULT_APPROVAL_TIMEOUT_MS,
  DEFAULT_HARNESS_CONFIG,
  approvalPatternKey,
  buildApprovalPreview,
  commandLineOf,
  rememberPatternFor,
  resolveApprovalTimeoutMs,
  scaffoldChainMemoryKey,
  type ApprovalCallback,
  type ApprovalDecision,
  type ApprovalDecisionInput,
  type ApprovalPolicy,
  type ApprovalPreview,
  type ApprovalRememberPattern,
  type ApprovalRequestInfo,
  type ApprovalResult,
  type HarnessConfig,
  type HarnessContext,
  type HarnessEvent,
  type PermissionKey,
  type ResourceUsage,
} from "./execution/index.ts";

export {
  DEFAULT_TOOLS,
  FETCH_URL_MAX_BODY_CHARS,
  FETCH_URL_MAX_CHARS,
  FETCH_URL_MAX_REDIRECTS,
  FETCH_URL_TIMEOUT_MS,
  DOWNLOAD_FILE_DEFAULT_MAX_BYTES,
  DOWNLOAD_FILE_MAX_REDIRECTS,
  DOWNLOAD_FILE_TIMEOUT_MS,
  IGNORED_DIRECTORY_NAMES,
  IMAGE_TOOLS_USER_AGENT,
  MAX_LIST_ENTRIES,
  MAX_TOOL_CALL_TIMEOUT_MS,
  MAX_BACKGROUND_JOBS_PER_TASK,
  JOB_OUTPUT_BUFFER_CHARS,
  JOB_STATUS_DEFAULT_TAIL_CHARS,
  JOB_STATUS_MAX_TAIL_CHARS,
  JOB_TEARDOWN_DRAIN_MS,
  SANDBOX_ALLOWLIST,
  SEARCH_IMAGES_DEFAULT_COUNT,
  SEARCH_IMAGES_MAX_COUNT,
  SEARCH_IMAGES_TIMEOUT_MS,
  ToolRegistry,
  VIEW_IMAGE_MAX_BYTES,
  BackgroundJobManager,
  applySearchReplace,
  commandKillTool,
  commandStatusTool,
  buildOpenverseQueryUrl,
  buildWikimediaQueryUrl,
  capFetchedText,
  clampCallTimeoutMs,
  createDefaultRegistry,
  createDirTool,
  createDownloadFileTool,
  createFetchUrlTool,
  createWebSearchTool,
  webSearchTool,
  parseDuckDuckGoHtml,
  webSearchBackend,
  createSearchImagesTool,
  changedLineCounts,
  decodeHtmlEntities,
  diffLines,
  downloadFileTool,
  editFileTool,
  editSearchReplaceTool,
  fetchUrlTool,
  globTool,
  grepTool,
  createGrepTool,
  parseRipgrepJson,
  ripgrepArgs,
  htmlToText,
  imageDimensions,
  isBlockedFetchHost,
  listDirTool,
  mergeImageResults,
  parseOpenverseResults,
  parseSearchReplaceBlocks,
  parseWikimediaResults,
  pathInWorkspace,
  readFileTool,
  renderPatch,
  runCommandTool,
  searchImagesTool,
  sniffImageMime,
  validateFetchTarget,
  viewImageTool,
  screenshotTool,
  createScreenshotTool,
  screenshotChromeArgs,
  walkTreeLines,
  writeFileTool,
  type AppliedSearchReplace,
  type BackgroundJob,
  type BackgroundJobHooks,
  type BackgroundJobState,
  type StartJobResult,
  type DiffLine,
  type DownloadFetchImpl,
  type DownloadFetchResponse,
  type FetchUrlImpl,
  type FetchUrlResponse,
  type ImageSearchFetchImpl,
  type ImageSearchResult,
  type ModelToolSchema,
  type ParsedSearchReplace,
  type SearchReplaceBlock,
  type ToolDefinition,
  type ToolExecutionContext,
} from "./tools/index.ts";

export {
  AGENT_MODE_ORDER,
  ASK_USER_TOOL_NAME,
  DEFAULT_QUESTION_TIMEOUT_MS,
  MODE_DESCRIPTIONS,
  ModeController,
  PLAN_DOCUMENTS_ROOT,
  PLAN_DOCUMENT_TEMPLATE,
  PRD_DOCUMENT_TEMPLATE,
  ARCHITECTURE_DOCUMENT_TEMPLATE,
  DESIGN_DOCUMENT_TEMPLATE,
  TASKS_DOCUMENT_TEMPLATE,
  PROVIDER_PRESETS,
  ProviderRegistry,
  ProviderRegistryStore,
  QuestionBroker,
  SLASH_COMMANDS,
  assembledPlanPath,
  hasPlanDocument,
  isPlanDocumentChange,
  parseTasksDocument,
  planDecisionsFromEvents,
  planDocumentRepairDirective,
  planSlugFromGoal,
  renderAssembledPlan,
  renderAssembledPlanDocuments,
  renderDecisionLines,
  PLAN_DOCUMENT_FILES,
  PLAN_DOCUMENT_TEMPLATES,
  type PlanDecision,
  SlashCommandRegistry,
  childTaskFromInput,
  MODE_PERMISSION_MATRIX,
  MAX_CHILD_SUMMARY_CHARS,
  classifyToolName,
  createAskUserTool,
  createSpawnSubagentTool,
  SPAWN_SUBAGENT_TOOL_NAME,
  backgroundFinishedNotice,
  cycleAgentMode,
  distillChildSummary,
  isPlanDocumentPath,
  isReadOnlyMode,
  isToolCallDenied,
  isToolVisible,
  maskApiKey,
  modeDenialMessage,
  modeIntent,
  modePromptContract,
  nextAgentMode,
  normalizeAgentMode,
  normalizeQuestionOptions,
  parseSlashCommand,
  questionResultOutput,
  restrictMode,
  resolveQuestionTimeoutMs,
  sanitizeProviderInput,
  seedProviderFromSettings,
  slashCommandSuggestions,
  toPublicProvider,
  toolCallPolicy,
  toolModePolicy,
  type AskUserToolDeps,
  type ChildFileChange,
  type ChildTaskExecution,
  type ChildTaskInput,
  type SpawnDispatch,
  type SpawnSubagentInput,
  type SpawnSubagentToolDeps,
  type ModeChange,
  type ParsedSlashCommand,
  type ProviderPreset,
  type SlashCommandContext,
  type SlashCommandResult,
  type UserQuestionInfo,
  type UserQuestionOption,
  type UserQuestionOutcome,
  type UserQuestionResult,
} from "./interaction/index.ts";

export {
  AgentLoop,
  CONDENSED_TOOL_OUTPUT,
  CONVERSATIONAL_SYSTEM_PROMPT,
  LOOP_HARD_PAUSE_AT,
  MAX_CONSECUTIVE_TIMEOUTS,
  STALL_ESCALATE_AT,
  STALL_LIMIT,
  schemaSummary,
  validateToolCallArguments,
  type ToolCallValidation,
  MAX_MENTION_DIR_ENTRIES,
  MAX_MENTION_FILE_CHARS,
  MAX_MENTION_PATHS,
  MAX_MENTION_TOTAL_CHARS,
  MAX_PINNED_FILES_IN_PROMPT,
  MAX_PINNED_LINES_PER_FILE,
  MAX_PINNED_TOTAL_CHARS,
  MAX_SKILL_DESCRIPTION_CHARS,
  MAX_SKILL_INDEX_CHARS,
  PROMPT_FAMILIES,
  QUESTION_SYSTEM_PROMPT,
  SCAFFOLD_RECIPES,
  UNSUPPORTED_FRAMEWORK_MENTIONS,
  DefaultContextManager,
  GLOBAL_RULES_LABEL,
  HOOKS_CONFIG_RELATIVE_PATH,
  LOOP_WINDOW_SIZE,
  LoopGuard,
  MAX_REVIEW_DIFF_CHARS,
  MAX_RULES_CHARS,
  PROJECT_RULES_FILES,
  REPEAT_SUPPRESSED_OUTPUT,
  REVIEW_READ_ONLY_TOOLS,
  type ContextManagerOptions,
  type SlideTaskParams,
  type DokumenTaskParams,
  type CreationCompletionEvidence,
  type CreationGoal,
  type CreationRefusal,
  type HookExecution,
  type HookPhase,
  type HookRule,
  type HooksConfig,
  type LoadHooksResult,
  type LoopGuardDecision,
  type LoopGuardObservation,
  type LoopRepeatKind,
  type PostToolHookOutcome,
  type PreToolHookOutcome,
  type ProjectRules,
  type ProjectRulesOptions,
  type ReviewFinding,
  type ReviewResult,
  type ScaffoldChainStep,
  type ScaffoldMatch,
  type ScaffoldRecipe,
  type ScaffoldHostInfo,
  type ScaffoldRecipeCategory,
  type ScaffoldRecipeId,
  type TaskTargetInput,
  type ToolchainProbe,
  type ToolchainProbeFn,
  BOOTSTRAP_PROBE_TOOLS,
  DEFAULT_SCAFFOLD_HOST,
  MISE_PACKAGE_BY_TOOL,
  buildReviewMessages,
  answerConversational,
  answerQuestion,
  classifyChatIntent,
  commandLineForCall,
  QUESTION_GATE_DIRECTIVE,
  commandLineTokens,
  compressCommandOutput,
  condenseToolOutputs,
  conversationalFallbackReply,
  creationCompletionRefusal,
  creationSpecificity,
  deriveTaskTargetDir,
  detectCommandOutputFamily,
  detectCreationGoal,
  detectPromptFamily,
  detectScaffoldRequest,
  detectUnsupportedFramework,
  djangoProjectName,
  explicitTargetFolder,
  extractMentionPaths,
  extractTargetDir,
  flutterProjectName,
  formatToolchainSummary,
  planDocumentFolder,
  gatherWorkspaceContext,
  missingToolchains,
  normalizePromptFamilySetting,
  parsePromptFamilySetting,
  pathInsideTarget,
  probeToolchains,
  promptFamilyFragment,
  questionFallbackReply,
  questionGateAppliesToGoal,
  recordedTargetDir,
  renderDatabasePlaybook,
  renderDockerGeneratorLine,
  renderScaffoldPlaybook,
  renderToolchainAcquisition,
  renderUnsupportedPlaybook,
  resolveMentionSection,
  resolvePromptFamily,
  scaffoldApprovalChain,
  scaffoldChainStepFor,
  scaffoldMarkerPresent,
  scaffoldPlanSteps,
  sessionAnchorDirective,
  summarizeCommandFailure,
  workspaceRelativePath,
  contextMeter,
  createPlan,
  isDefaultPipeline,
  estimateMessageTokens,
  evaluateStopConditions,
  handleObservation,
  hookMatches,
  hookNoteLine,
  interpretTask,
  loadHooksConfig,
  loadProjectRules,
  loopGuidanceNote,
  noProgressCondition,
  parseAction,
  parseReviewFindings,
  replan,
  resolveToolOutputLimits,
  reviewDiff,
  runPostToolHooks,
  runPreToolHooks,
  shapeToolOutput,
  stableSerialize,
  thoughtFromMessage,
  toolCallParseErrorOutput,
  toolCallSignature,
  truncate,
  truncateHeadTail,
  unstagedDiff,
  writeSpillFile,
  DEFAULT_TOOL_OUTPUT_LIMITS,
  OUTPUT_COMPRESSION_MIN_CHARS,
  OUTPUT_COMPRESSION_MIN_LINES,
  TOOL_OUTPUT_HEAD_RATIO,
  TOOL_OUTPUT_MAX_CHARS,
  TOOL_OUTPUT_MAX_LINES,
  type Action,
  type AgentLoopOptions,
  type AnswerQuestionOptions,
  type ChatIntent,
  type CommandOutputCompression,
  type CommandOutputCompressionInput,
  type CommandOutputFamily,
  type CompleteAction,
  type ContextManager,
  type Observation,
  type ObservationHandler,
  type Planner,
  type ReplanAction,
  type ShapeToolOutputOptions,
  type ShapedToolOutput,
  type StopAction,
  type StopCondition,
  type StopPolicy,
  type StopReason,
  type TaskInterpreter,
  type ToolAction,
  type ToolExecutor,
  type ToolOutputLimits,
} from "./agent/index.ts";

export {
  MAX_EDIT_DIAGNOSTIC_LINES,
  guardEditedFile,
  type EditGuardLsp,
  type EditGuardOptions,
  type EditGuardOutcome,
} from "./agent/edit-guard.ts";

export {
  DEFAULT_LLM_TIMEOUT_MS,
  DEFAULT_MODEL_COOLDOWN_MS,
  DEFAULT_RETRY_POLICY,
  LLMAuthError,
  LLMContentPolicyError,
  LLMError,
  LLMFormatError,
  LLMRateLimitError,
  LLMTimeoutError,
  ModelPoolProvider,
  OpenAICompatProvider,
  TextProtocolProvider,
  asModelController,
  buildPrompt,
  classifyLLMError,
  classifyProviderError,
  clearProviders,
  createProviderForConfig,
  createProviderFromSettings,
  defaultTemplate,
  estimateTokens,
  getProvider,
  hasUpstreamFailureMarker,
  instrumentProvider,
  isFatalLLMError,
  isModelPoolRetryableError,
  isRetryable,
  isToolSchemaInvalidError,
  isTransientLLMError,
  modelPoolFailureReason,
  normalizeModelList,
  normalizeModelTiers,
  normalizeToolParameters,
  normalizeToolProtocol,
  normalizeToolSchemas,
  parseModelStrategy,
  parseModelTiers,
  parseTextToolCalls,
  parseToolProtocol,
  protocolBlock,
  registerProvider,
  strongestModelFor,
  systemMessage,
  tierRankForPhase,
  toTextMessages,
  userMessage,
  withRetry,
  type ChatOptions,
  type ChatResponse,
  type ContentBlock,
  type ImageContent,
  type LLMProvider,
  type LLMErrorKind,
  type Message,
  type ModelController,
  type ModelPhase,
  type ModelPoolOptions,
  type ModelPoolSwitch,
  type OpenAICompatOptions,
  type PromptSection,
  type PromptTemplate,
  type ProtocolSwitchInfo,
  type RetryPolicy,
  type Role,
  type StreamChunk,
  type TextContent,
  type TextParseResult,
  type TextProtocolOptions,
  type ToolDefinition as LLMToolDefinition,
} from "./providers/index.ts";

export {
  AgentRegistry,
  WORKSPACE_AGENTS_RELATIVE_PATH,
  agentNameFromPath,
  loadAgents,
  parseAgentMarkdown,
  workspaceAgentsDir,
  type AgentDefinition,
} from "./agents/index.ts";

export {
  applyTaskWorktree,
  createTaskWorktree,
  isGitWorkTree,
  removeTaskWorktree,
  taskBranchName,
  worktreeChangedFiles,
  worktreePatch,
  worktreePathFor,
  type WorktreeRecord,
} from "./worktree.ts";

export {
  DECK_DIRNAME,
  DECK_FILENAME,
  DECK_ASSETS_DIRNAME,
  MAX_SLIDES,
  LONG_TEXT_CHARS,
  deckPaths,
  deckRelativePaths,
  slugifyTitle,
  type DeckSpec,
  type DeckTheme,
  type Slide,
  type SlideTemplateRef,
  type BlockPosition,
  type DeckIssue,
} from "./slides/deck.ts";

export {
  LAYOUTS,
  LAYOUT_IDS,
  TEMPLATE_PAGE_LAYOUT,
  getLayout,
  layoutBlockKeys,
  validateSlideContent,
  type LayoutDef,
  type LayoutCategory,
  type LayoutSchema,
  type PropSchema,
  type PropSchemaType,
} from "./slides/layouts.ts";

export {
  ensureDeckDir,
  readDeck,
  writeDeck,
  newDeck,
  newDeckId,
  newSlideId,
  validateDeck,
  summarizeDeck,
  type ValidateDeckOptions,
} from "./slides/store.ts";

export { exportDeckToPptx, type PptxExportResult, type ExportDeckOptions } from "./slides/export-pptx.ts";
export {
  exportTemplateDeckToPptx,
  rewriteTemplateSlideText,
  TemplateCloneError,
  type TemplateCloneExportResult,
} from "./slides/export-template.ts";

export {
  generateDeckOutlineStage,
  fillDeckSlidesStage,
  generateDeckFullStage,
  regenerateSlideStage,
  normalizeBrief,
  assignTemplatePages,
  templateSkeletonContent,
  SlidePipelineError,
  type DeckBrief,
  type OutlineItem,
  type TemplateOutlineItem,
  type FillStageResult,
  type ExportInfo,
} from "./slides/pipeline.ts";

export {
  SlideEngine,
  applyDeckOps,
  type SlideEngineDeps,
  type SlideEngineOutcome,
  type SlideEngineRunResult,
} from "./slides/engine.ts";

export {
  SLIDE_TEMPLATES,
  getSlideTemplate,
  listSlideTemplates,
  type SlideTemplate,
} from "./slides/templates.ts";

export {
  PPT_TEMPLATES_DIR,
  MAX_PPTX_TEMPLATE_BYTES,
  pptxTemplatesDir,
  extractPptxDesign,
  savePptxTemplate,
  listPptxTemplates,
  getPptxTemplate,
  readPptxTemplateBackground,
  readPptxTemplateSource,
  readPptxTemplateSync,
  readPptxTemplateAsset,
  deletePptxTemplate,
  applyPptxTemplateTheme,
  PptxTemplateError,
  type PptxTemplate,
  type PptxSlideSize,
  type ExtractedPptxDesign,
} from "./slides/pptx-template.ts";

export {
  extractPptxPages,
  extractPptxPageAddresses,
  listPptxSlideParts,
  matchPageAddresses,
  prefixPageAssets,
  pptxTemplateAssetFiles,
  templatePageTextSlots,
  templatePageImageSlots,
  validateTemplateSlideSlots,
  slotMaxChars,
  type PptxTemplatePage,
  type PptxTemplatePageKind,
  type PptxTemplateSlot,
  type PptxTextSlot,
  type PptxImageSlot,
  type PptxSlotRect,
  type PptxPagesExtract,
  type PptxDecorShape,
  type PptxTemplatePageAddress,
  type PptxTemplateSlotAddress,
} from "./slides/pptx-pages.ts";

export {
  BUILTIN_TEMPLATES,
  BUILTIN_KINDS,
  DEFAULT_BUILTIN_TEMPLATE_ID,
  IMAGE_LAYOUT_IDS,
  getBuiltinTemplate,
  listBuiltinTemplates,
  builtinDeckTheme,
  builtinTemplateForTheme,
  builtinKindOfLayout,
  assignBuiltinLayouts,
  emptyImageFields,
  furnitureRect,
  pageChipRect,
  type BuiltinTemplate,
  type BuiltinSlideKind,
  type FurnitureSpec,
  type FurnitureElement,
  type FurnitureColorRole,
  type FurnitureAnchor,
  type BuiltinTypography,
} from "./slides/builtin-templates.ts";

export {
  extractSlideWords,
  pourDeckIntoTemplate,
  type SlideWords,
  type PourDeckResult,
} from "./slides/pour.ts";

export {
  createDeckTool,
  readDeckTool,
  addSlideTool,
  updateSlideTool,
  moveSlideTool,
  deleteSlideTool,
  setDeckThemeTool,
  validateDeckTool,
  exportDeckTool,
  SLIDE_TOOLS,
} from "./tools/index.ts";

export {
  documentDir,
  documentPaths,
  documentsRoot,
  activePointerPath,
  savedSchemasDir,
  dokumenArchiveDir,
  type DokumenKind,
  type DokumenSubMode,
  type FieldType,
  type FieldDef,
  type ExtractionTarget,
  type DokumenSchema,
  type FieldStatus,
  type Provenance,
  type FieldValue,
  type RecordCheck,
  type RecordDecision,
  type ExtractRecord,
  type SourceStatus,
  type SourceInfo,
  type SectionStatus,
  type DokumenSection,
  type StyleOp,
  type ExportRecord,
  type Citation,
  type DocumentState,
  type ParsedBlock,
  type ParsedSource,
} from "./dokumen/document.ts";

export {
  newDocumentId,
  newSourceId,
  newRecordId,
  newSectionId,
  newStyleOpId,
  newDocument,
  writeDocument,
  readDocument,
  readActiveDocument,
  setActiveDocument,
  createActiveDocument,
  appendAudit,
  readAudit,
  ingestSourceFile,
  sourceFilePath,
  writeParsedBlocks,
  readParsedBlocks,
  readSavedSchema,
  saveSchema,
  listSavedSchemas,
  archiveActiveDocument,
  type SavedSchema,
} from "./dokumen/store.ts";

export {
  SUPPORTED_SOURCE_EXTENSIONS,
  isSupportedSource,
  parseSourceFile,
  parseSourceBytes,
  pageChunks,
  findProvenance,
} from "./dokumen/parse.ts";

export {
  AUTO_CLEAR_MIN,
  ESCALATE_BELOW,
  parseNumber,
  parseDate,
  normalizeValue,
  validateRecord,
  isVerified,
  decisionCounts,
} from "./dokumen/validate.ts";

export { exportData, type DataExportResult } from "./dokumen/export-data.ts";
export { buildDocumentDocxBytes, exportDocumentDocx, exportDocumentPdf, type DocumentExportResult } from "./dokumen/export-docx.ts";

export {
  inspectDocxStyles,
  proposeStyleOps,
  parseStyleInstruction,
  applyStyleOps,
  type DocxStyleState,
  type StyleTarget,
} from "./dokumen/style-ops.ts";

export {
  MAX_STAGE_ATTEMPTS as DOKUMEN_MAX_STAGE_ATTEMPTS,
  DokumenPipelineError,
  structuredCall as dokumenStructuredCall,
  classifyStage,
  proposeSchemaStage,
  extractSourceStage,
  proposeOutlineStage,
  draftSectionStage,
  criticStage,
  type OutlineItem as DokumenOutlineItem,
  type CitationMaterial,
} from "./dokumen/pipeline.ts";

export { DokumenWebTools, parseDuckDuckGo, type SearchHit, type WebFetch } from "./dokumen/web.ts";

export { DokumenEngine, type DokumenRunEvent, type DokumenEngineOptions, type DokumenRunOptions, type DokumenAskUser } from "./dokumen/engine.ts";

export {
  workbookRelativePaths,
  slugifyTitle as sheetSlugifyTitle,
  colToIndex,
  indexToCol,
  parseCellRef,
  formatCellRef,
  parseRange,
  sheetBounds,
  sheetHeaders,
  tileRefs,
  tileIssues,
  WORKBOOK_DIRNAME,
  WORKBOOK_FILENAME,
  type CellScalar,
  type SheetCell,
  type SheetSpec,
  type ChartSpec,
  type PivotSpec,
  type PivotValueSpec,
  type DashboardTileSpec,
  type SlicerSpec,
  type ConditionalFormatSpec,
  type DataValidationSpec,
  type ColumnType,
  type BlueprintColumn,
  type BlueprintSheet,
  type BlueprintAssumption,
  type BlueprintDashboard,
  type SheetBlueprint,
  type VerifyCellIssue,
  type VerifyReport,
  type SheetExportRecord,
  type WorkbookStage,
  type WorkbookSpec,
  type WorkbookIssue,
} from "./sheets/workbook.ts";
export {
  newWorkbookId,
  newSheetId,
  newWorkbook,
  newSheet,
  workbookPaths,
  ensureWorkbookDir,
  readWorkbook,
  writeWorkbook,
  validateWorkbook,
  summarizeWorkbook,
  readRangeValues,
  type SheetSummary,
  type WorkbookSummary,
} from "./sheets/store.ts";
export {
  parseFormula,
  evaluateFormula,
  evaluateWorkbook,
  createEvalContext,
  displayValue,
  formatWithNumFmt,
  type EvalResult,
  type EvalError,
  type WorkbookEvaluation,
} from "./sheets/evaluator.ts";
export {
  SHEET_OP_NAMES,
  applySheetOps,
  shiftFormulaRefs,
  type SheetOpName,
  type SheetOpResult,
  type ApplySheetOpsResult,
} from "./sheets/ops.ts";
export {
  parseCsvText,
  inferScalar,
  rowsToSheet,
  importCsvToWorkbook,
  importXlsxToWorkbook,
  inferColumnType,
} from "./sheets/import.ts";
export {
  composeDashboard,
  layoutTileAnchors,
  materializeTile,
  clearTile,
  tileSlug,
  DEFAULT_TILE_ACCENT,
} from "./sheets/dashboard.ts";
export {
  buildExcelJsWorkbook,
  exportWorkbookToXlsx,
  dashboardComposition,
  appendFormulaSummaryFallback,
  exportSheetToCsvText,
  exportWorkbookCsv,
  probeSheetSidecar,
  resolveSheetSidecar,
  runSheetSidecar,
  sidecarCandidates,
  sheetSidecarCacheDir,
  sheetSidecarSourceDir,
  SHEET_SIDECAR_BINARY,
  type SidecarSpec,
  type SidecarRunResult,
  type SidecarProbe,
  type SidecarDiscoverySeams,
  type SidecarResolveSeams,
  type SheetSidecarResolution,
} from "./sheets/export.ts";
export {
  verifyWorkbook,
  verifyWorkbookCore,
  libreOfficeRecalc,
  detectSoffice,
  ERROR_LITERALS,
  type VerifyOptions,
  type LibreOfficeRecalcResult,
} from "./sheets/verify.ts";
export {
  generateBlueprintStage,
  fillSheetRowsStage,
  validateBlueprint,
  validateFillRows,
  structuredCall as sheetStructuredCall,
  SheetPipelineError,
  type BlueprintStageInput,
  type FillStageInput,
  type FillStageResult as SheetFillStageResult,
} from "./sheets/pipeline.ts";
export {
  SpreadsheetEngine,
  type SpreadsheetEngineDeps,
  type SpreadsheetEngineOutcome,
  type SpreadsheetEngineRunResult,
} from "./sheets/engine.ts";

export { VERSION } from "./version.ts";
