/**
 * Daedalus Core — public API.
 *
 * Phase 1 exposes foundation primitives only: shared contracts, the in-process
 * event bus, structured logging, typed settings, and per-task persistence.
 * Agent/tool/LLM logic is intentionally absent (PLAN.md Phase 1 scope).
 *
 * Contracts:  TaskSpec, Plan, PlanStep, ToolCall, ToolResult, Event,
 *             ValidationResult, RecoveryAction, FinalReport, EVENT_TYPES
 * Runtime:    EventBus, TaskStore, createLogger, loadSettings, redactSettings
 */
export {
  AGENT_MODES,
  EVENT_TYPES,
  type AgentMode,
  type Attachment,
  type AttachmentKind,
  type ChildTask,
  type ChildTaskBudget,
  type EditFormat,
  type Event,
  type EventType,
  type FinalReport,
  type ModelStrategy,
  type ModelTier,
  type Plan,
  type PlanStep,
  type PlanStepStatus,
  type PromptFamily,
  type TailorEscalatedPayload,
  type PromptFamilySetting,
  type ProviderConfig,
  type ProviderConfigPublic,
  type RecoveryAction,
  type ReviewGateReport,
  type SlashCommand,
  type TaskSpec,
  type TaskState,
  type ToolCall,
  type ToolModePolicy,
  type ToolProtocol,
  type ToolResult,
  type ToolResultStatus,
  type ToolVisibility,
  type ValidationCheck,
  type ValidationResult,
  type WorktreeReport,
} from "./contracts.ts";

export { EventBus, emitEvent, type EventHandler, type EventTarget } from "./events.ts";

export {
  createLogger,
  type LogLevel,
  type Logger,
} from "./logger.ts";

export {
  loadSettings,
  normalizeEditFormat,
  parseEditFormat,
  redactSettings,
  resolveDaedalusHome,
  type Env,
  type Settings,
} from "./settings.ts";

export { TaskStore } from "./persistence.ts";

export {
  MAX_PINS,
  PINS_FILE_NAME,
  loadPins,
  pinsFilePath,
  sanitizePins,
  savePins,
} from "./pins.ts";

export {
  ansiPalette,
  bold,
  dim,
  fg,
  getPalette,
  modeAccent,
  palette,
  paletteLight,
  rgb,
  supportsColor,
  type ModeAccentKey,
  type PaletteName,
} from "./theme.ts";

export {
  EXIT_CODES,
  TaskRunner,
  exitCodeFor,
  planDocumentsFromEvents,
  type ExtensionStatus,
  type RunOptions,
  type RunOutcome,
  type RunResult,
  type TaskRunnerOptions,
} from "./runtime.ts";

export {
  McpClient,
  McpManager,
  loadMcpConfig,
  MCP_CONFIG_RELATIVE_PATH,
  type McpCallResult,
  type McpRemoteTool,
  type McpServerConfig,
  type McpServerStatus,
} from "./mcp/index.ts";

export {
  LspClient,
  LspManager,
  formatDiagnostic,
  loadLspConfig,
  LSP_CONFIG_RELATIVE_PATH,
  type LspDiagnostic,
  type LspServerConfig,
  type LspServerStatus,
} from "./lsp/index.ts";

export {
  MAX_SKILLS_IN_PROMPT,
  SKILLS_CONFIG_RELATIVE_PATH,
  SkillRegistry,
  createReadSkillTool,
  daedalusGlobalSkillsDir,
  dedupeSkillsByName,
  formatSkillOrigin,
  globalSkillSearchDirs,
  loadSkillConfig,
  loadSkillInventory,
  loadSkills,
  parseSkillConfig,
  parseSkillMarkdown,
  renderSkillBody,
  resolveSkillSearchDirs,
  setSkillDisabled,
  skillsConfigPath,
  workspaceSkillsDir,
  writeSkillConfig,
  WORKSPACE_SKILLS_RELATIVE_PATH,
  type Skill,
  type SkillConfig,
  type SkillDirOptions,
  type SkillInfo,
  type SkillInventoryEntry,
  type SkillLoadedPayload,
  type SkillOrigin,
  type SkillSearchDir,
} from "./skills/index.ts";

export {
  CommandValidator,
  VALIDATION_PROFILE_RELATIVE_PATH,
  aggregateValidation,
  completionGate,
  decideRecovery,
  discoverChecks,
  discoverScopedChecks,
  discoverTargetChecks,
  loadValidationProfile,
  normalizeError,
  profileCommands,
  splitCommandLine,
  type NormalizedError,
  type RecoveryContext,
  type RecoveryPolicy,
  type ScopedCheckDiscovery,
  type TargetCheckDiscovery,
  type ValidationCommand,
  type ValidationProfile,
  type ValidationProfileCheck,
  type Validator,
  type ValidatorOptions,
  validationFailed,
  validationFailureSignature,
  validationPassed,
  validationSatisfied,
} from "./validation/index.ts";

export {
  ApprovalBroker,
  ExecutionHarness,
  DEFAULT_APPROVAL_TIMEOUT_MS,
  DEFAULT_HARNESS_CONFIG,
  approvalPatternKey,
  buildApprovalPreview,
  commandLineOf,
  rememberPatternFor,
  resolveApprovalTimeoutMs,
  scaffoldChainMemoryKey,
  type ApprovalCallback,
  type ApprovalDecision,
  type ApprovalDecisionInput,
  type ApprovalPolicy,
  type ApprovalPreview,
  type ApprovalRememberPattern,
  type ApprovalRequestInfo,
  type ApprovalResult,
  type HarnessConfig,
  type HarnessContext,
  type HarnessEvent,
  type PermissionKey,
  type ResourceUsage,
} from "./execution/index.ts";

export {
  DEFAULT_TOOLS,
  FETCH_URL_MAX_BODY_CHARS,
  FETCH_URL_MAX_CHARS,
  FETCH_URL_MAX_REDIRECTS,
  FETCH_URL_TIMEOUT_MS,
  DOWNLOAD_FILE_DEFAULT_MAX_BYTES,
  DOWNLOAD_FILE_MAX_REDIRECTS,
  DOWNLOAD_FILE_TIMEOUT_MS,
  IGNORED_DIRECTORY_NAMES,
  IMAGE_TOOLS_USER_AGENT,
  MAX_LIST_ENTRIES,
  MAX_TOOL_CALL_TIMEOUT_MS,
  MAX_BACKGROUND_JOBS_PER_TASK,
  JOB_OUTPUT_BUFFER_CHARS,
  JOB_STATUS_DEFAULT_TAIL_CHARS,
  JOB_STATUS_MAX_TAIL_CHARS,
  SANDBOX_ALLOWLIST,
  SEARCH_IMAGES_DEFAULT_COUNT,
  SEARCH_IMAGES_MAX_COUNT,
  SEARCH_IMAGES_TIMEOUT_MS,
  ToolRegistry,
  VIEW_IMAGE_MAX_BYTES,
  BackgroundJobManager,
  applySearchReplace,
  commandKillTool,
  commandStatusTool,
  buildOpenverseQueryUrl,
  buildWikimediaQueryUrl,
  capFetchedText,
  clampCallTimeoutMs,
  createDefaultRegistry,
  createDirTool,
  createDownloadFileTool,
  createFetchUrlTool,
  createSearchImagesTool,
  changedLineCounts,
  decodeHtmlEntities,
  diffLines,
  downloadFileTool,
  editFileTool,
  editSearchReplaceTool,
  fetchUrlTool,
  globTool,
  grepTool,
  htmlToText,
  imageDimensions,
  isBlockedFetchHost,
  listDirTool,
  mergeImageResults,
  parseOpenverseResults,
  parseSearchReplaceBlocks,
  parseWikimediaResults,
  pathInWorkspace,
  readFileTool,
  renderPatch,
  runCommandTool,
  searchImagesTool,
  sniffImageMime,
  validateFetchTarget,
  viewImageTool,
  walkTreeLines,
  writeFileTool,
  type AppliedSearchReplace,
  type BackgroundJob,
  type BackgroundJobHooks,
  type BackgroundJobState,
  type StartJobResult,
  type DiffLine,
  type DownloadFetchImpl,
  type DownloadFetchResponse,
  type FetchUrlImpl,
  type FetchUrlResponse,
  type ImageSearchFetchImpl,
  type ImageSearchResult,
  type ModelToolSchema,
  type ParsedSearchReplace,
  type SearchReplaceBlock,
  type ToolDefinition,
  type ToolExecutionContext,
} from "./tools/index.ts";

export {
  AGENT_MODE_ORDER,
  ASK_USER_TOOL_NAME,
  DEFAULT_QUESTION_TIMEOUT_MS,
  MODE_DESCRIPTIONS,
  ModeController,
  PLAN_DOCUMENTS_ROOT,
  PLAN_DOCUMENT_TEMPLATE,
  PRD_DOCUMENT_TEMPLATE,
  ARCHITECTURE_DOCUMENT_TEMPLATE,
  DESIGN_DOCUMENT_TEMPLATE,
  TASKS_DOCUMENT_TEMPLATE,
  PROVIDER_PRESETS,
  ProviderRegistry,
  ProviderRegistryStore,
  QuestionBroker,
  SLASH_COMMANDS,
  assembledPlanPath,
  hasPlanDocument,
  isPlanDocumentChange,
  parseTasksDocument,
  planDecisionsFromEvents,
  planDocumentRepairDirective,
  planSlugFromGoal,
  renderAssembledPlan,
  renderAssembledPlanDocuments,
  renderDecisionLines,
  PLAN_DOCUMENT_FILES,
  PLAN_DOCUMENT_TEMPLATES,
  type PlanDecision,
  SlashCommandRegistry,
  childTaskFromInput,
  MODE_PERMISSION_MATRIX,
  MAX_CHILD_SUMMARY_CHARS,
  classifyToolName,
  createAskUserTool,
  createSpawnSubagentTool,
  SPAWN_SUBAGENT_TOOL_NAME,
  backgroundFinishedNotice,
  cycleAgentMode,
  distillChildSummary,
  isPlanDocumentPath,
  isReadOnlyMode,
  isToolCallDenied,
  isToolVisible,
  maskApiKey,
  modeDenialMessage,
  modeIntent,
  modePromptContract,
  nextAgentMode,
  normalizeAgentMode,
  normalizeQuestionOptions,
  parseSlashCommand,
  questionResultOutput,
  restrictMode,
  resolveQuestionTimeoutMs,
  sanitizeProviderInput,
  seedProviderFromSettings,
  slashCommandSuggestions,
  toPublicProvider,
  toolCallPolicy,
  toolModePolicy,
  type AskUserToolDeps,
  type ChildFileChange,
  type ChildTaskExecution,
  type ChildTaskInput,
  type SpawnDispatch,
  type SpawnSubagentInput,
  type SpawnSubagentToolDeps,
  type ModeChange,
  type ParsedSlashCommand,
  type ProviderPreset,
  type SlashCommandContext,
  type SlashCommandResult,
  type UserQuestionInfo,
  type UserQuestionOption,
  type UserQuestionOutcome,
  type UserQuestionResult,
} from "./interaction/index.ts";

export {
  AgentLoop,
  CONDENSED_TOOL_OUTPUT,
  CONVERSATIONAL_SYSTEM_PROMPT,
  LOOP_HARD_PAUSE_AT,
  MAX_CONSECUTIVE_TIMEOUTS,
  STALL_ESCALATE_AT,
  STALL_LIMIT,
  schemaSummary,
  validateToolCallArguments,
  type ToolCallValidation,
  MAX_MENTION_DIR_ENTRIES,
  MAX_MENTION_FILE_CHARS,
  MAX_MENTION_PATHS,
  MAX_MENTION_TOTAL_CHARS,
  MAX_PINNED_FILES_IN_PROMPT,
  MAX_PINNED_LINES_PER_FILE,
  MAX_PINNED_TOTAL_CHARS,
  MAX_SKILL_DESCRIPTION_CHARS,
  MAX_SKILL_INDEX_CHARS,
  PROMPT_FAMILIES,
  QUESTION_SYSTEM_PROMPT,
  SCAFFOLD_RECIPES,
  UNSUPPORTED_FRAMEWORK_MENTIONS,
  DefaultContextManager,
  GLOBAL_RULES_LABEL,
  HOOKS_CONFIG_RELATIVE_PATH,
  LOOP_WINDOW_SIZE,
  LoopGuard,
  MAX_REVIEW_DIFF_CHARS,
  MAX_RULES_CHARS,
  PROJECT_RULES_FILES,
  REPEAT_SUPPRESSED_OUTPUT,
  REVIEW_READ_ONLY_TOOLS,
  type ContextManagerOptions,
  type CreationCompletionEvidence,
  type CreationGoal,
  type CreationRefusal,
  type HookExecution,
  type HookPhase,
  type HookRule,
  type HooksConfig,
  type LoadHooksResult,
  type LoopGuardDecision,
  type LoopGuardObservation,
  type LoopRepeatKind,
  type PostToolHookOutcome,
  type PreToolHookOutcome,
  type ProjectRules,
  type ProjectRulesOptions,
  type ReviewFinding,
  type ReviewResult,
  type ScaffoldChainStep,
  type ScaffoldMatch,
  type ScaffoldRecipe,
  type ScaffoldHostInfo,
  type ScaffoldRecipeCategory,
  type ScaffoldRecipeId,
  type TaskTargetInput,
  type ToolchainProbe,
  type ToolchainProbeFn,
  BOOTSTRAP_PROBE_TOOLS,
  DEFAULT_SCAFFOLD_HOST,
  MISE_PACKAGE_BY_TOOL,
  buildReviewMessages,
  answerConversational,
  answerQuestion,
  classifyChatIntent,
  commandLineForCall,
  QUESTION_GATE_DIRECTIVE,
  commandLineTokens,
  compressCommandOutput,
  condenseToolOutputs,
  conversationalFallbackReply,
  creationCompletionRefusal,
  creationSpecificity,
  deriveTaskTargetDir,
  detectCommandOutputFamily,
  detectCreationGoal,
  detectPromptFamily,
  detectScaffoldRequest,
  detectUnsupportedFramework,
  djangoProjectName,
  explicitTargetFolder,
  extractMentionPaths,
  extractTargetDir,
  flutterProjectName,
  formatToolchainSummary,
  planDocumentFolder,
  gatherWorkspaceContext,
  missingToolchains,
  normalizePromptFamilySetting,
  parsePromptFamilySetting,
  pathInsideTarget,
  probeToolchains,
  promptFamilyFragment,
  questionFallbackReply,
  questionGateAppliesToGoal,
  renderDatabasePlaybook,
  renderDockerGeneratorLine,
  renderScaffoldPlaybook,
  renderToolchainAcquisition,
  renderUnsupportedPlaybook,
  resolveMentionSection,
  resolvePromptFamily,
  scaffoldApprovalChain,
  scaffoldChainStepFor,
  scaffoldMarkerPresent,
  scaffoldPlanSteps,
  summarizeCommandFailure,
  workspaceRelativePath,
  contextMeter,
  createPlan,
  isDefaultPipeline,
  estimateMessageTokens,
  evaluateStopConditions,
  handleObservation,
  hookMatches,
  hookNoteLine,
  interpretTask,
  loadHooksConfig,
  loadProjectRules,
  loopGuidanceNote,
  noProgressCondition,
  parseAction,
  parseReviewFindings,
  replan,
  resolveToolOutputLimits,
  reviewDiff,
  runPostToolHooks,
  runPreToolHooks,
  shapeToolOutput,
  stableSerialize,
  thoughtFromMessage,
  toolCallParseErrorOutput,
  toolCallSignature,
  truncate,
  truncateHeadTail,
  unstagedDiff,
  writeSpillFile,
  DEFAULT_TOOL_OUTPUT_LIMITS,
  OUTPUT_COMPRESSION_MIN_CHARS,
  OUTPUT_COMPRESSION_MIN_LINES,
  TOOL_OUTPUT_HEAD_RATIO,
  TOOL_OUTPUT_MAX_CHARS,
  TOOL_OUTPUT_MAX_LINES,
  type Action,
  type AgentLoopOptions,
  type AnswerQuestionOptions,
  type ChatIntent,
  type CommandOutputCompression,
  type CommandOutputCompressionInput,
  type CommandOutputFamily,
  type CompleteAction,
  type ContextManager,
  type Observation,
  type ObservationHandler,
  type Planner,
  type ReplanAction,
  type ShapeToolOutputOptions,
  type ShapedToolOutput,
  type StopAction,
  type StopCondition,
  type StopPolicy,
  type StopReason,
  type TaskInterpreter,
  type ToolAction,
  type ToolExecutor,
  type ToolOutputLimits,
} from "./agent/index.ts";

export {
  MAX_EDIT_DIAGNOSTIC_LINES,
  guardEditedFile,
  type EditGuardLsp,
  type EditGuardOptions,
  type EditGuardOutcome,
} from "./agent/edit-guard.ts";

export {
  DEFAULT_LLM_TIMEOUT_MS,
  DEFAULT_MODEL_COOLDOWN_MS,
  DEFAULT_RETRY_POLICY,
  LLMAuthError,
  LLMContentPolicyError,
  LLMError,
  LLMFormatError,
  LLMRateLimitError,
  LLMTimeoutError,
  ModelPoolProvider,
  OpenAICompatProvider,
  TextProtocolProvider,
  asModelController,
  buildPrompt,
  classifyLLMError,
  classifyProviderError,
  clearProviders,
  createProviderForConfig,
  createProviderFromSettings,
  defaultTemplate,
  estimateTokens,
  getProvider,
  hasUpstreamFailureMarker,
  instrumentProvider,
  isFatalLLMError,
  isModelPoolRetryableError,
  isRetryable,
  isTransientLLMError,
  modelPoolFailureReason,
  normalizeModelList,
  normalizeModelTiers,
  normalizeToolProtocol,
  parseModelStrategy,
  parseModelTiers,
  parseTextToolCalls,
  parseToolProtocol,
  protocolBlock,
  registerProvider,
  strongestModelFor,
  systemMessage,
  tierRankForPhase,
  toTextMessages,
  userMessage,
  withRetry,
  type ChatOptions,
  type ChatResponse,
  type ContentBlock,
  type ImageContent,
  type LLMProvider,
  type LLMErrorKind,
  type Message,
  type ModelController,
  type ModelPhase,
  type ModelPoolOptions,
  type ModelPoolSwitch,
  type OpenAICompatOptions,
  type PromptSection,
  type PromptTemplate,
  type ProtocolSwitchInfo,
  type RetryPolicy,
  type Role,
  type StreamChunk,
  type TextContent,
  type TextParseResult,
  type TextProtocolOptions,
  type ToolDefinition as LLMToolDefinition,
} from "./providers/index.ts";

export {
  AgentRegistry,
  WORKSPACE_AGENTS_RELATIVE_PATH,
  agentNameFromPath,
  loadAgents,
  parseAgentMarkdown,
  workspaceAgentsDir,
  type AgentDefinition,
} from "./agents/index.ts";

export {
  applyTaskWorktree,
  createTaskWorktree,
  isGitWorkTree,
  removeTaskWorktree,
  taskBranchName,
  worktreeChangedFiles,
  worktreePatch,
  worktreePathFor,
  type WorktreeRecord,
} from "./worktree.ts";

export { VERSION } from "./version.ts";
